import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const brandColor = Color(0xFF123B5D);
const accentColor = Color(0xFF2E7D9A);
const clientsStorageKey = 'dp_manager_pro.clients.v1';
const projectsStorageKey = 'dp_manager_pro.projects.v1';

void main() => runApp(const DPManagerProApp());

class DPManagerProApp extends StatelessWidget {
  const DPManagerProApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'DP Manager Pro', theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: brandColor), scaffoldBackgroundColor: const Color(0xFFF5F7FA)), home: const HomePage());
}

class Client {
  Client({required this.name, this.phone = '', this.email = '', this.company = ''});
  String name, phone, email, company;
  Map<String, dynamic> toJson() => {'name': name, 'phone': phone, 'email': email, 'company': company};
  factory Client.fromJson(Map<String, dynamic> j) => Client(name: j['name']?.toString() ?? '', phone: j['phone']?.toString() ?? '', email: j['email']?.toString() ?? '', company: j['company']?.toString() ?? '');
}

class Project {
  Project({required this.name, required this.clientName, this.status = 'En cours', this.amount = 0, this.startDate = '', this.endDate = ''});
  String name, clientName, status, startDate, endDate;
  double amount;
  Map<String, dynamic> toJson() => {'name': name, 'clientName': clientName, 'status': status, 'amount': amount, 'startDate': startDate, 'endDate': endDate};
  factory Project.fromJson(Map<String, dynamic> j) => Project(name: j['name']?.toString() ?? '', clientName: j['clientName']?.toString() ?? '', status: j['status']?.toString() ?? 'En cours', amount: (j['amount'] as num?)?.toDouble() ?? 0, startDate: j['startDate']?.toString() ?? '', endDate: j['endDate']?.toString() ?? '');
}

class Storage {
  static final SharedPreferencesAsync prefs = SharedPreferencesAsync();
  static Future<List<Client>> clients() async { try { final r = await prefs.getString(clientsStorageKey); if (r == null) return []; final d = jsonDecode(r) as List; return d.map((e) => Client.fromJson(Map<String,dynamic>.from(e))).toList(); } catch (_) { return []; } }
  static Future<bool> saveClients(List<Client> v) async { try { return await prefs.setString(clientsStorageKey, jsonEncode(v.map((e)=>e.toJson()).toList())); } catch (_) { return false; } }
  static Future<List<Project>> projects() async { try { final r = await prefs.getString(projectsStorageKey); if (r == null) return []; final d = jsonDecode(r) as List; return d.map((e) => Project.fromJson(Map<String,dynamic>.from(e))).toList(); } catch (_) { return []; } }
  static Future<bool> saveProjects(List<Project> v) async { try { return await prefs.setString(projectsStorageKey, jsonEncode(v.map((e)=>e.toJson()).toList())); } catch (_) { return false; } }
}

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage> {
  int selectedIndex=0; List<Client> clients=[]; List<Project> projects=[]; bool loading=true;
  final items=const [(Icons.dashboard_outlined,'Tableau de bord'),(Icons.people_outline,'Clients'),(Icons.business_outlined,'Chantiers'),(Icons.request_quote_outlined,'Devis'),(Icons.receipt_long_outlined,'Factures'),(Icons.payments_outlined,'Paiements'),(Icons.shopping_cart_outlined,'Dépenses'),(Icons.bar_chart_outlined,'Rapports')];
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { clients=await Storage.clients(); projects=await Storage.projects(); if(mounted)setState(()=>loading=false); }
  @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator())); return LayoutBuilder(builder:(context,c){final desktop=c.maxWidth>=900; return Scaffold(appBar:desktop?null:AppBar(title:const Text('DP Manager Pro')),drawer:desktop?null:Drawer(child:_menu()),body:Row(children:[if(desktop)_sidebar(),Expanded(child:selectedIndex==1?_clientsPage():selectedIndex==2?_projectsPage():_dashboard(desktop))]));});}
  Widget _sidebar()=>Container(width:255,color:brandColor,child:SafeArea(child:Column(children:[const Padding(padding:EdgeInsets.all(22),child:Row(children:[CircleAvatar(backgroundColor:Colors.white,child:Icon(Icons.business_center,color:brandColor)),SizedBox(width:12),Text('DP Manager Pro',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold))])),Expanded(child:_menu()),const Padding(padding:EdgeInsets.all(18),child:Text('Version 0.2.0',style:TextStyle(color:Colors.white60)))])));
  Widget _menu()=>Container(color:brandColor,child:SafeArea(child:ListView.builder(padding:const EdgeInsets.symmetric(horizontal:12),itemCount:items.length,itemBuilder:(context,i)=>ListTile(selected:selectedIndex==i,selectedTileColor:Colors.white.withValues(alpha:.14),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(10)),leading:Icon(items[i].$1,color:Colors.white),title:Text(items[i].$2,style:const TextStyle(color:Colors.white)),onTap:(){setState(()=>selectedIndex=i);if(MediaQuery.sizeOf(context).width<900)Navigator.pop(context);}))));
  Widget _dashboard(bool desktop)=>SingleChildScrollView(padding:EdgeInsets.all(desktop?32:20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Tableau de bord',style:TextStyle(fontSize:32,fontWeight:FontWeight.w800,color:brandColor)),const SizedBox(height:6),const Text('Bienvenue dans DP Manager Pro',style:TextStyle(color:Colors.black54,fontSize:16)),const SizedBox(height:28),Wrap(spacing:16,runSpacing:16,children:[_stat('Clients','${clients.length}',Icons.people_outline),_stat('Chantiers','${projects.length}',Icons.business_outlined),_stat('Chantiers actifs','${projects.where((p)=>p.status=="En cours").length}',Icons.construction_outlined),_stat('CA chantiers','${projects.fold<double>(0,(s,p)=>s+p.amount).toStringAsFixed(0)} FCFA',Icons.payments_outlined)]),const SizedBox(height:28),Card(child:Padding(padding:const EdgeInsets.all(24),child:Row(children:[const CircleAvatar(backgroundColor:Color(0xFFE7F0F4),child:Icon(Icons.auto_graph,color:accentColor)),const SizedBox(width:16),Expanded(child:Text('${projects.isEmpty?'Commencez par créer votre premier chantier.':'Vos chantiers sont enregistrés automatiquement.'}',style:const TextStyle(color:Colors.black54)))])))]));
  Widget _stat(String t,String v,IconData i)=>SizedBox(width:245,child:Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:brandColor.withValues(alpha:.1),borderRadius:BorderRadius.circular(12)),child:Icon(i,color:brandColor)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:Colors.black54)),const SizedBox(height:5),Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800,color:brandColor))]))]))));
  Widget _clientsPage()=>_simpleList('Clients','Gérez vos clients et leurs coordonnées.',clients.isEmpty?'Aucun client pour le moment':'${clients.length} client(s)',Icons.people_outline,()=>_openClientForm());
  Widget _simpleList(String title,String sub,String empty,IconData icon,VoidCallback add)=>SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800,color:brandColor)),const SizedBox(height:5),Text(sub,style:const TextStyle(color:Colors.black54))])),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:Text('Nouveau ${title.substring(0,title.length-1).toLowerCase()}'))]),const SizedBox(height:20),Expanded(child:Center(child:Text(empty)))])));
  Widget _projectsPage()=>SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Chantiers',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800,color:brandColor)),SizedBox(height:5),Text('Suivez vos travaux, clients, montants et statuts.',style:TextStyle(color:Colors.black54))])),FilledButton.icon(onPressed:()=>_openProjectForm(),icon:const Icon(Icons.add),label:const Text('Nouveau chantier'))]),const SizedBox(height:20),Expanded(child:projects.isEmpty?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.business_outlined,size:64,color:Colors.black26),const SizedBox(height:12),const Text('Aucun chantier pour le moment',style:TextStyle(fontSize:18,fontWeight:FontWeight.w600)),const SizedBox(height:8),const Text('Créez votre premier chantier.',style:TextStyle(color:Colors.black54))])):ListView.separated(itemCount:projects.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(context,i){final p=projects[i];return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.construction)),title:Text(p.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${p.clientName} • ${p.amount.toStringAsFixed(0)} FCFA • ${p.status}'),trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')_openProjectForm(project:p);if(v=='delete')_deleteProject(p);},itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('Modifier')),PopupMenuItem(value:'delete',child:Text('Supprimer'))])));}))])));
  Future<void> _openClientForm({Client? client})async{final r=await showDialog<Client>(context:context,builder:(_)=>ClientFormDialog(client:client));if(r==null)return;if(client==null)setState(()=>clients.add(r));else setState((){client.name=r.name;client.phone=r.phone;client.email=r.email;client.company=r.company;});final ok=await Storage.saveClients(clients);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'Client enregistré avec succès.':'Impossible d’enregistrer le client.')));}
  Future<void> _deleteProject(Project p)async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Supprimer le chantier ?'),content:Text('Voulez-vous supprimer « ${p.name} » ?'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Annuler')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Supprimer'))]));if(ok==true){setState(()=>projects.remove(p));await Storage.saveProjects(projects);}}
  Future<void> _openProjectForm({Project? project})async{final r=await showDialog<Project>(context:context,builder:(_)=>ProjectFormDialog(project:project,clients:clients));if(r==null)return;if(project==null)setState(()=>projects.add(r));else setState((){project.name=r.name;project.clientName=r.clientName;project.status=r.status;project.amount=r.amount;project.startDate=r.startDate;project.endDate=r.endDate;});final ok=await Storage.saveProjects(projects);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'Chantier enregistré avec succès.':'Impossible d’enregistrer le chantier.')));}
}

class ClientFormDialog extends StatefulWidget{const ClientFormDialog({super.key,this.client});final Client? client;@override State<ClientFormDialog> createState()=>_ClientFormDialogState();}
class _ClientFormDialogState extends State<ClientFormDialog>{final keyForm=GlobalKey<FormState>();late final TextEditingController name,phone,email,company;@override void initState(){super.initState();final c=widget.client;name=TextEditingController(text:c?.name??'');phone=TextEditingController(text:c?.phone??'');email=TextEditingController(text:c?.email??'');company=TextEditingController(text:c?.company??'');}@override void dispose(){name.dispose();phone.dispose();email.dispose();company.dispose();super.dispose();}@override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.client==null?'Nouveau client':'Modifier le client'),content:SizedBox(width:480,child:Form(key:keyForm,child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:name,decoration:const InputDecoration(labelText:'Nom complet *'),validator:(v)=>v==null||v.trim().isEmpty?'Le nom est obligatoire':null),const SizedBox(height:12),TextFormField(controller:company,decoration:const InputDecoration(labelText:'Entreprise')),const SizedBox(height:12),TextFormField(controller:phone,decoration:const InputDecoration(labelText:'Téléphone'),keyboardType:TextInputType.phone),const SizedBox(height:12),TextFormField(controller:email,decoration:const InputDecoration(labelText:'E-mail'),keyboardType:TextInputType.emailAddress)]))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Annuler')),FilledButton(onPressed:(){if(!keyForm.currentState!.validate())return;Navigator.pop(context,Client(name:name.text.trim(),phone:phone.text.trim(),email:email.text.trim(),company:company.text.trim()));},child:const Text('Enregistrer'))]);}

class ProjectFormDialog extends StatefulWidget{const ProjectFormDialog({super.key,this.project,required this.clients});final Project? project;final List<Client> clients;@override State<ProjectFormDialog> createState()=>_ProjectFormDialogState();}
class _ProjectFormDialogState extends State<ProjectFormDialog>{final keyForm=GlobalKey<FormState>();late final TextEditingController name,amount,startDate,endDate;late String clientName,status;@override void initState(){super.initState();final p=widget.project;name=TextEditingController(text:p?.name??'');amount=TextEditingController(text:p==null?'':p.amount.toStringAsFixed(0));startDate=TextEditingController(text:p?.startDate??'');endDate=TextEditingController(text:p?.endDate??'');clientName=p?.clientName??(widget.clients.isNotEmpty?widget.clients.first.name:'');status=p?.status??'En cours';}@override void dispose(){name.dispose();amount.dispose();startDate.dispose();endDate.dispose();super.dispose();}@override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.project==null?'Nouveau chantier':'Modifier le chantier'),content:SizedBox(width:500,child:Form(key:keyForm,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextFormField(controller:name,decoration:const InputDecoration(labelText:'Nom du chantier *'),validator:(v)=>v==null||v.trim().isEmpty?'Le nom est obligatoire':null),const SizedBox(height:12),DropdownButtonFormField<String>(value:clientName.isEmpty?null:clientName,decoration:const InputDecoration(labelText:'Client *'),items:widget.clients.map((c)=>DropdownMenuItem(value:c.name,child:Text(c.name))).toList(),onChanged:widget.clients.isEmpty?null:(v)=>setState(()=>clientName=v??''),validator:(v)=>v==null||v.isEmpty?'Sélectionnez un client':null),const SizedBox(height:12),DropdownButtonFormField<String>(value:status,decoration:const InputDecoration(labelText:'Statut'),items:const['En cours','En attente','Terminé','Annulé'].map((s)=>DropdownMenuItem(value:s,child:Text(s))).toList(),onChanged:(v)=>setState(()=>status=v??'En cours')),const SizedBox(height:12),TextFormField(controller:amount,decoration:const InputDecoration(labelText:'Montant (FCFA)'),keyboardType:TextInputType.number,validator:(v)=>double.tryParse(v?.replaceAll(' ','')??'')==null?'Entrez un montant valide':null),const SizedBox(height:12),TextFormField(controller:startDate,decoration:const InputDecoration(labelText:'Date de début (JJ/MM/AAAA)')),const SizedBox(height:12),TextFormField(controller:endDate,decoration:const InputDecoration(labelText:'Date de fin (JJ/MM/AAAA)'))])))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Annuler')),FilledButton(onPressed:(){if(!keyForm.currentState!.validate())return;final value=double.tryParse(amount.text.replaceAll(' ',''))??0;Navigator.pop(context,Project(name:name.text.trim(),clientName:clientName,status:status,amount:value,startDate:startDate.text.trim(),endDate:endDate.text.trim()));},child:const Text('Enregistrer'))]);}
